# Generated by Django 4.1 on 2022-08-17 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weater.city')),
                ('data', models.DateField(default=datetime.datetime(2022, 8, 17, 14, 48, 18, 699555, tzinfo=datetime.timezone.utc))),
                ('temperature', models.FloatField()),
            ],
            bases=('weater.city',),
        ),
    ]
