# Generated by Django 4.1 on 2022-08-17 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 15, 7, 36, 859963, tzinfo=datetime.timezone.utc)),
        ),
    ]
