# Generated by Django 4.1 on 2022-08-21 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
